name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windows-build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install scons
        run: pip install scons

      - name: Install svn
        run: choco install svn zip

      - name: Setup GtkRadiant
        run: scons target=setup

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build GtkRadiant
        run: msbuild /p:Configuration=Release /p:Platform=Win32 /target:radiant

      - name: Build q3map2 x64
        run: msbuild /p:Configuration=Release /p:Platform=x64 /target:q3map2

      - name: Create archive
        run: zip -r GtkRadiant.zip install

      - uses: actions/upload-artifact@v2
        with:
          name: Upload
          path: GtkRadiant.zip
